include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: warning
    mixin_inherits_from_not_object: ignore

  exclude:
    - test/*
    - lib/firebase_options.dart
    - lib/presentation/localisations.g.dart

linter:
  rules:
    always_specify_types: true
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    public_member_api_docs: false
    omit_local_variable_types: false
